### ISSUE TITLE
possible duplication of telemetry events

### ISSUE THREAD

**Issue by edublancas** [ploomber/core#19]
we recently ran a [workshop](https://github.com/ploomber/pydata-nyc-22/blob/main/workshop.ipynb), and most attendees ran the code locally. then, we saw an uptick of events in posthog that didn't match the number of attendees: we had about 20 attendees but saw >100 new users on posthog. I suspect this has to do with https://github.com/ploomber/core/pull/15, but I'm unsure.

the workshop covers a few of our projects, but I suspect the problem is with the *Running experiments in parallel* section, which runs this [pipeline](https://github.com/ploomber/pydata-nyc-22/tree/main/parallel).

We need to investigate if this is still an issue and fix it.

FYI: @idomic

**Comment by yafimvo** [comment]
Yes, It seems like the problem happens when we use the parallel executor and we check if it's the 1st usage.

```python
def check_first_time_usage():
    """
    The function checks for first time usage if the conf file exists and the
    uid file doesn't exist.
    """
    internal = Internal()
    first_time = internal.first_time
    internal.first_time = False
    return first_time
```

Since the default values of the Internal config file are these:

```python
class Internal(Config):
    """
    Internal file to store settings (not intended to be modified by the
    user)
    """
    last_version_check: datetime.datetime = None
    uid: str
    first_time: bool = True

    def uid_default(self):
        return str(uuid4())
```

If we use parallel, and each process sees an empty config file, it gets the default values and creates a new user id. Since we're using `internal = Internal()` a lot of times this happens often.

I implemented a solution in this [PR](https://github.com/ploomber/core/pull/20)

I tried to reduce the number of writes to this config file and changed the `check_first_time_usage` logic to read directly from the configuration file. I ran the workshop locally and it seems to solve this duplications issue and didn't affect the tests.
